//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 2009-4-17 23:14:29
namespace OmeiEDM
{
    
    /// <summary>
    /// There are no comments for OmeiDocumentEntity in the schema.
    /// </summary>
    public partial class OmeiDocumentEntity : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new OmeiDocumentEntity object using the connection string found in the 'OmeiDocumentEntity' section of the application configuration file.
        /// </summary>
        public OmeiDocumentEntity() : 
                base("name=OmeiDocumentEntity", "OmeiDocumentEntity")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new OmeiDocumentEntity object.
        /// </summary>
        public OmeiDocumentEntity(string connectionString) : 
                base(connectionString, "OmeiDocumentEntity")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new OmeiDocumentEntity object.
        /// </summary>
        public OmeiDocumentEntity(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "OmeiDocumentEntity")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for EDM_OmeiDocumentSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EDM_OmeiDocument> EDM_OmeiDocumentSet
        {
            get
            {
                if ((this._EDM_OmeiDocumentSet == null))
                {
                    this._EDM_OmeiDocumentSet = base.CreateQuery<EDM_OmeiDocument>("[EDM_OmeiDocumentSet]");
                }
                return this._EDM_OmeiDocumentSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EDM_OmeiDocument> _EDM_OmeiDocumentSet;
        /// <summary>
        /// There are no comments for EDM_OmeiDocumentSet in the schema.
        /// </summary>
        public void AddToEDM_OmeiDocumentSet(EDM_OmeiDocument eDM_OmeiDocument)
        {
            base.AddObject("EDM_OmeiDocumentSet", eDM_OmeiDocument);
        }
    }
    /// <summary>
    /// There are no comments for OmeiTravelModel.EDM_OmeiDocument in the schema.
    /// </summary>
    /// <KeyProperties>
    /// docName
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="OmeiTravelModel", Name="EDM_OmeiDocument")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EDM_OmeiDocument : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EDM_OmeiDocument object.
        /// </summary>
        /// <param name="docName">Initial value of docName.</param>
        /// <param name="docNotes">Initial value of docNotes.</param>
        /// <param name="docTitle">Initial value of docTitle.</param>
        /// <param name="docContent">Initial value of docContent.</param>
        public static EDM_OmeiDocument CreateEDM_OmeiDocument(string docName, string docNotes, string docTitle, string docContent)
        {
            EDM_OmeiDocument eDM_OmeiDocument = new EDM_OmeiDocument();
            eDM_OmeiDocument.docName = docName;
            eDM_OmeiDocument.docNotes = docNotes;
            eDM_OmeiDocument.docTitle = docTitle;
            eDM_OmeiDocument.docContent = docContent;
            return eDM_OmeiDocument;
        }
        /// <summary>
        /// There are no comments for Property docName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string docName
        {
            get
            {
                return this._docName;
            }
            set
            {
                this.OndocNameChanging(value);
                this.ReportPropertyChanging("docName");
                this._docName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("docName");
                this.OndocNameChanged();
            }
        }
        private string _docName;
        partial void OndocNameChanging(string value);
        partial void OndocNameChanged();
        /// <summary>
        /// There are no comments for Property docNotes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string docNotes
        {
            get
            {
                return this._docNotes;
            }
            set
            {
                this.OndocNotesChanging(value);
                this.ReportPropertyChanging("docNotes");
                this._docNotes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("docNotes");
                this.OndocNotesChanged();
            }
        }
        private string _docNotes;
        partial void OndocNotesChanging(string value);
        partial void OndocNotesChanged();
        /// <summary>
        /// There are no comments for Property docTitle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string docTitle
        {
            get
            {
                return this._docTitle;
            }
            set
            {
                this.OndocTitleChanging(value);
                this.ReportPropertyChanging("docTitle");
                this._docTitle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("docTitle");
                this.OndocTitleChanged();
            }
        }
        private string _docTitle;
        partial void OndocTitleChanging(string value);
        partial void OndocTitleChanged();
        /// <summary>
        /// There are no comments for Property docContent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string docContent
        {
            get
            {
                return this._docContent;
            }
            set
            {
                this.OndocContentChanging(value);
                this.ReportPropertyChanging("docContent");
                this._docContent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("docContent");
                this.OndocContentChanged();
            }
        }
        private string _docContent;
        partial void OndocContentChanging(string value);
        partial void OndocContentChanged();
    }
}
